//
// Created by Sp4rk on 09-08-17.
//

#ifndef CES_KEYPRESSURFACES_H
#define CES_KEYPRESSURFACES_H

typedef enum {
    KEY_PRESS_SURFACE_DEFAULT,
    KEY_PRESS_SURFACE_UP,
    KEY_PRESS_SURFACE_DOWN,
    KEY_PRESS_SURFACE_LEFT,
    KEY_PRESS_SURFACE_RIGHT,
    KEY_PRESS_SURFACE_TOTAL,
} KeyPressSurfaces;

#endif //CES_KEYPRESSURFACES_H
